<a href="https://colab.research.google.com/github/Caosbot/Treinos_Python/blob/Machine_Learning/modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Inicio

In [49]:
import pandas as pd
import numpy as np
from sklearn import datasets

## Usando dataset do sklearn

In [50]:
#housing = datasets.fetch_california_housing()

In [51]:
#print(housing)

In [52]:
#df = pd.DataFrame(housing.data, columns=housing.feature_names)

In [53]:
#df.head()

In [54]:
#print(housing.DESCR)

In [55]:
#print(housing.target)

In [56]:
#X = housing.data
#y = housing.target

## Com Bonston.csv

In [57]:
df_Boston = pd.read_csv(r"F:\Cursos\DNC\Banco de dados\Boston.csv", sep = ",")

In [58]:
df_Boston.head()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [59]:
df_Boston.drop(['Unnamed: 0'], axis=1, inplace=True)

In [60]:
target= df_Boston['medv']
target

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [61]:
df_Boston.drop(columns=['medv'], inplace=True)

In [62]:
df_Boston.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33

In [63]:
X = df_Boston.values
y = target.values

### Modelo



1.   Regreção Linear do SKLEARN
2.   Suport Vector Regression SKLEARN
3.   Decision Tree Regression XGBoost

Modeling Assumptions: Apenas variaveis numéricas
Sem Hiperparametros para os 3 modelos (Default)

In [64]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor

In [65]:
from sklearn.svm import SVR

#### Dataset Split 20%

In [66]:
X_train, X_test, y_train, y_test  = train_test_split(X,y, train_size = 0.8, test_size=0.2,random_state = 42)

#### Treino

In [67]:
regLinear = LinearRegression().fit(X_train,y_train) #Testando o modelo
yLinear =  regLinear.predict(X_test) #Para predizer os valores de casas

### Tecnica 1 . Regressão Linear

#### Métrica MSE e RMSE
Mean score error
Root Mean Squared Error
Para penalizar erros de previsão

In [68]:
MSELinear = mean_squared_error(y_test, yLinear) #Comparando os valores

In [69]:
print(f"MSE: {MSELinear}")
print(f"RMSE: {np.sqrt(MSELinear)}") #Erro em torno de até

MSE: 24.291119474973442
RMSE: 4.928602182665329

### Tecnica 2. SVR

In [70]:
regSVR = SVR().fit(X_train,y_train) #Treinando o modelo
ySVR = regSVR.predict(X_test) #Testando o modelo

In [71]:
MSESVR = mean_squared_error(y_test, ySVR)

In [72]:
print(f"MSE: {MSESVR}")
print(f"RMSE: {np.sqrt(MSESVR)}") #Erro em torno de até

MSE: 52.83836576796669
RMSE: 7.269000327965785

### Tecnica 3 Decision Tree Regression (XGBosst)

In [73]:
regXGB = XGBRegressor().fit(X_train,y_train) #Treinando o modelo
yXGB = regXGB.predict(X_test) #Testando o modelo

In [74]:
MSEXGB =mean_squared_error(y_test, yXGB)

In [75]:
print(f"MSE: {MSEXGB}")
print(f"RMSE: {np.sqrt(MSEXGB)}") #Erro em torno de até

MSE: 6.909231565384943
RMSE: 2.62854171840299

## Otimização de Hiperparametros

Aplicando metodo de GridSearch do SKLEARN

In [76]:
regXGB.get_params().keys()

dict_keys(['objective', 'base_score', 'booster', 'callbacks', 'colsample_bylevel', 'colsample_bynode', 'colsample_bytree', 'device', 'early_stopping_rounds', 'enable_categorical', 'eval_metric', 'feature_types', 'gamma', 'grow_policy', 'importance_type', 'interaction_constraints', 'learning_rate', 'max_bin', 'max_cat_threshold', 'max_cat_to_onehot', 'max_delta_step', 'max_depth', 'max_leaves', 'min_child_weight', 'missing', 'monotone_constraints', 'multi_strategy', 'n_estimators', 'n_jobs', 'num_parallel_tree', 'random_state', 'reg_alpha', 'reg_lambda', 'sampling_method', 'scale_pos_weight', 'subsample', 'tree_method', 'validate_parameters', 'verbosity'])

In [77]:
parametros = {
    "max_depth": [5,6,7], "learning_rate":[0.1, 0.2, 0.3,],
    "objective": ['reg:squarederror'], "booster": ['gbtree'],
    "n_jobs": [5], "gamma": [0,1], "min_child_weight":[1,3],
    "max_delta_step": [0,1], "subsample": [0.5, 1]
    }

In [78]:
xgbGrid = GridSearchCV(XGBRegressor(), parametros, refit='neg_mean_square_error', verbose=True)

In [79]:
xgbGridModel = xgbGrid.fit(X_train,y_train)

Fitting 5 folds for each of 144 candidates, totalling 720 fits

In [80]:
xgbGridModel.best_params_

{'booster': 'gbtree',
 'gamma': 0,
 'learning_rate': 0.2,
 'max_delta_step': 0,
 'max_depth': 5,
 'min_child_weight': 1,
 'n_jobs': 5,
 'objective': 'reg:squarederror',
 'subsample': 0.5}

In [81]:
yGrid = xgbGridModel.predict(X_test)

In [82]:
MSEGrid = mean_squared_error(y_test,yGrid)

In [48]:
print(f"MSE XBG: {MSEGrid}")
print(f"RMSE XGB: {np.sqrt(MSEGrid)}") #Erro em torno de até

MSE XBG: 8.2975112347883
RMSE XGB: 2.8805400942858443